name: "Publish to test PyPI"

on:
  push:

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: |
          uv python install 3.10
          uv venv -p 3.10
          source .venv/bin/activate
          uv sync
          uv sync --dev

      - name: Build
        run: uv build --verbose

      - name: Test
        run: uv run pytest

      - name: Documentation
        run: |
          source .venv/bin/activate
          uv sync --dev
          sphinx-build doc/source/ doc/build
      
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/

      - name: Publish
        if: ${{ github.ref_name	 == 'master' }}
        run: |
          source .venv/bin/activate
          uv sync --dev
          check-wheel-contents dist/*.whl
          twine upload -r testpypi -u __token__ -p ${{ secrets.PYPI_TEST_TOKEN }} --verbose dist/*
          # uv publish --index testpypi -t ${{ secrets.PYPI_TEST_TOKEN }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: freewili-dist-${{ github.sha }}
          path: |
            dist/
            doc/build/
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: run
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          